-- Fix Raihana's ID Mismatch
-- The issue is that the User ID in 'public.users' (b10fcd4d...) does not match the 
-- Authenticated User ID (fc1cfe42...) generated by Supabase Auth.
-- This mismatch makes the system think she is NOT the admin found in the database.

BEGIN;

DO $$
DECLARE
  -- The correct Auth ID (from your terminal logs)
  v_auth_id UUID := 'fc1cfe42-1044-40ca-8b43-54b0849b5504';
  
  -- The incorrect Public ID (from your screenshot/database)
  v_old_id UUID := 'b10fcd4d-be9e-42c7-ab4d-47baaac9189d';
  
  -- Variables to hold data
  v_email TEXT;
  v_hash TEXT;
  v_role TEXT;
  v_first_name TEXT;
  v_last_name TEXT;
  v_pic TEXT;
BEGIN
  -- 1. Fetch current data for Raihana
  SELECT email, password_hash, role, first_name, last_name, profile_picture_url
  INTO v_email, v_hash, v_role, v_first_name, v_last_name, v_pic
  FROM users 
  WHERE id = v_old_id;

  IF v_email IS NOT NULL THEN
      -- 2. Rename the old record's email to release the UNIQUE constraint
      UPDATE users 
      SET email = 'TEMP_' || v_email 
      WHERE id = v_old_id;

      -- 3. Insert the NEW user record with the CORRECT ID
      INSERT INTO users (id, email, password_hash, role, first_name, last_name, profile_picture_url, is_active, email_verified, created_at, updated_at)
      VALUES (v_auth_id, v_email, v_hash, v_role, v_first_name, v_last_name, v_pic, true, true, now(), now());

      -- 4. Update all related tables to point to the NEW ID
      
      -- Mentor Profiles
      UPDATE mentor_profiles SET user_id = v_auth_id WHERE user_id = v_old_id;
      
      -- Student Profiles (unlikely for admin, but safe to do)
      UPDATE student_profiles SET user_id = v_auth_id WHERE user_id = v_old_id;
      
      -- Batches (as mentor)
      UPDATE batches SET mentor_id = v_auth_id WHERE mentor_id = v_old_id;
      
      -- Batch Mentors (if she is a co-mentor)
      UPDATE batch_mentors SET mentor_id = v_auth_id WHERE mentor_id = v_old_id;
      
      -- Notices (as author)
      UPDATE notices SET author_id = v_auth_id WHERE author_id = v_old_id;
      
      -- Practice Decks (as creator)
      UPDATE practice_decks SET created_by = v_auth_id WHERE created_by = v_old_id;
      
      -- Roadmap Discussions
      UPDATE roadmap_discussions SET user_id = v_auth_id WHERE user_id = v_old_id;
      
      -- Live Sessions
      UPDATE live_sessions SET mentor_id = v_auth_id WHERE mentor_id = v_old_id;
      
      -- User Sessions
      UPDATE user_sessions SET user_id = v_auth_id WHERE user_id = v_old_id;

      -- 5. Delete the OLD record (now that it has no dependencies)
      DELETE FROM users WHERE id = v_old_id;
      
      RAISE NOTICE 'Fixed ID mismatch for user %', v_email;
  ELSE
      RAISE NOTICE 'User ID % not found in public.users, skipping...', v_old_id;
  END IF;

END $$;

COMMIT;
